//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://purolator.com/pws/datatypes/v1", ClrNamespace="purolator.com.pws.datatypes.v1")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.microsoft.com/practices/EnterpriseLibrary/2007/01/wcf/validation", ClrNamespace="www.microsoft.com.practices.EnterpriseLibrary._2007._01.wcf.validation")]

namespace purolator.com.pws.datatypes.v1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestContext", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class RequestContext : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string VersionField;
        
        private purolator.com.pws.datatypes.v1.Language LanguageField;
        
        private string GroupIDField;
        
        private string RequestReferenceField;
        
        private string UserTokenField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public purolator.com.pws.datatypes.v1.Language Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string GroupID
        {
            get
            {
                return this.GroupIDField;
            }
            set
            {
                this.GroupIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string RequestReference
        {
            get
            {
                return this.RequestReferenceField;
            }
            set
            {
                this.RequestReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string UserToken
        {
            get
            {
                return this.UserTokenField;
            }
            set
            {
                this.UserTokenField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Language", Namespace="http://purolator.com/pws/datatypes/v1")]
    public enum Language : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        en = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fr = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseContext", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class ResponseContext : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ResponseReferenceField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ResponseReference
        {
            get
            {
                return this.ResponseReferenceField;
            }
            set
            {
                this.ResponseReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestContainer", Namespace="http://purolator.com/pws/datatypes/v1")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(purolator.com.pws.datatypes.v1.TrackPackagesByReferenceRequestContainer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(purolator.com.pws.datatypes.v1.GetDeliveryDetailsRequestContainer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(purolator.com.pws.datatypes.v1.TrackPackagesByPinRequestContainer))]
    public partial class RequestContainer : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrackPackagesByReferenceRequestContainer", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class TrackPackagesByReferenceRequestContainer : purolator.com.pws.datatypes.v1.RequestContainer
    {
        
        private purolator.com.pws.datatypes.v1.TrackPackageByReferenceSearchCriteria TrackPackageByReferenceSearchCriteriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public purolator.com.pws.datatypes.v1.TrackPackageByReferenceSearchCriteria TrackPackageByReferenceSearchCriteria
        {
            get
            {
                return this.TrackPackageByReferenceSearchCriteriaField;
            }
            set
            {
                this.TrackPackageByReferenceSearchCriteriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDeliveryDetailsRequestContainer", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class GetDeliveryDetailsRequestContainer : purolator.com.pws.datatypes.v1.RequestContainer
    {
        
        private purolator.com.pws.datatypes.v1.PIN PINField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public purolator.com.pws.datatypes.v1.PIN PIN
        {
            get
            {
                return this.PINField;
            }
            set
            {
                this.PINField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrackPackagesByPinRequestContainer", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class TrackPackagesByPinRequestContainer : purolator.com.pws.datatypes.v1.RequestContainer
    {
        
        private purolator.com.pws.datatypes.v1.PIN[] PINsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public purolator.com.pws.datatypes.v1.PIN[] PINs
        {
            get
            {
                return this.PINsField;
            }
            set
            {
                this.PINsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PIN", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class PIN : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrackPackageByReferenceSearchCriteria", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class TrackPackageByReferenceSearchCriteria : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ReferenceField;
        
        private string DestinationPostalCodeField;
        
        private string DestinationCountryCodeField;
        
        private string BillingAccountNumberField;
        
        private string ShipmentFromDateField;
        
        private string ShipmentToDateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Reference
        {
            get
            {
                return this.ReferenceField;
            }
            set
            {
                this.ReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string DestinationPostalCode
        {
            get
            {
                return this.DestinationPostalCodeField;
            }
            set
            {
                this.DestinationPostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string DestinationCountryCode
        {
            get
            {
                return this.DestinationCountryCodeField;
            }
            set
            {
                this.DestinationCountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string BillingAccountNumber
        {
            get
            {
                return this.BillingAccountNumberField;
            }
            set
            {
                this.BillingAccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string ShipmentFromDate
        {
            get
            {
                return this.ShipmentFromDateField;
            }
            set
            {
                this.ShipmentFromDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string ShipmentToDate
        {
            get
            {
                return this.ShipmentToDateField;
            }
            set
            {
                this.ShipmentToDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseContainer", Namespace="http://purolator.com/pws/datatypes/v1")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(purolator.com.pws.datatypes.v1.TrackPackagesByReferenceResponseContainer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(purolator.com.pws.datatypes.v1.GetDeliveryDetailsResponseContainer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(purolator.com.pws.datatypes.v1.TrackPackagesByPinResponseContainer))]
    public partial class ResponseContainer : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private purolator.com.pws.datatypes.v1.ResponseInformation ResponseInformationField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public purolator.com.pws.datatypes.v1.ResponseInformation ResponseInformation
        {
            get
            {
                return this.ResponseInformationField;
            }
            set
            {
                this.ResponseInformationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseInformation", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class ResponseInformation : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private purolator.com.pws.datatypes.v1.Error[] ErrorsField;
        
        private purolator.com.pws.datatypes.v1.InformationalMessage[] InformationalMessagesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public purolator.com.pws.datatypes.v1.Error[] Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public purolator.com.pws.datatypes.v1.InformationalMessage[] InformationalMessages
        {
            get
            {
                return this.InformationalMessagesField;
            }
            set
            {
                this.InformationalMessagesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrackPackagesByReferenceResponseContainer", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class TrackPackagesByReferenceResponseContainer : purolator.com.pws.datatypes.v1.ResponseContainer
    {
        
        private purolator.com.pws.datatypes.v1.TrackingInformation[] TrackingInformationListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public purolator.com.pws.datatypes.v1.TrackingInformation[] TrackingInformationList
        {
            get
            {
                return this.TrackingInformationListField;
            }
            set
            {
                this.TrackingInformationListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDeliveryDetailsResponseContainer", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class GetDeliveryDetailsResponseContainer : purolator.com.pws.datatypes.v1.ResponseContainer
    {
        
        private purolator.com.pws.datatypes.v1.DeliveryScan DeliveryDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public purolator.com.pws.datatypes.v1.DeliveryScan DeliveryDetails
        {
            get
            {
                return this.DeliveryDetailsField;
            }
            set
            {
                this.DeliveryDetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrackPackagesByPinResponseContainer", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class TrackPackagesByPinResponseContainer : purolator.com.pws.datatypes.v1.ResponseContainer
    {
        
        private purolator.com.pws.datatypes.v1.TrackingInformation[] TrackingInformationListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public purolator.com.pws.datatypes.v1.TrackingInformation[] TrackingInformationList
        {
            get
            {
                return this.TrackingInformationListField;
            }
            set
            {
                this.TrackingInformationListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrackingInformation", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class TrackingInformation : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private purolator.com.pws.datatypes.v1.PIN PINField;
        
        private purolator.com.pws.datatypes.v1.Scan[] ScansField;
        
        private purolator.com.pws.datatypes.v1.ResponseInformation ResponseInformationField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public purolator.com.pws.datatypes.v1.PIN PIN
        {
            get
            {
                return this.PINField;
            }
            set
            {
                this.PINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public purolator.com.pws.datatypes.v1.Scan[] Scans
        {
            get
            {
                return this.ScansField;
            }
            set
            {
                this.ScansField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public purolator.com.pws.datatypes.v1.ResponseInformation ResponseInformation
        {
            get
            {
                return this.ResponseInformationField;
            }
            set
            {
                this.ResponseInformationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class Error : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodeField;
        
        private string DescriptionField;
        
        private string AdditionalInformationField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string AdditionalInformation
        {
            get
            {
                return this.AdditionalInformationField;
            }
            set
            {
                this.AdditionalInformationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InformationalMessage", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class InformationalMessage : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodeField;
        
        private string MessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Scan", Namespace="http://purolator.com/pws/datatypes/v1")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(purolator.com.pws.datatypes.v1.InternationalOutboundScan))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(purolator.com.pws.datatypes.v1.UndeliverableScan))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(purolator.com.pws.datatypes.v1.OnDeliveryScan))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(purolator.com.pws.datatypes.v1.ProofOfPickUpScan))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(purolator.com.pws.datatypes.v1.DeliveryScan))]
    public partial class Scan : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ScanTypeField;
        
        private purolator.com.pws.datatypes.v1.PIN PINField;
        
        private purolator.com.pws.datatypes.v1.Depot DepotField;
        
        private string ScanDateField;
        
        private string ScanTimeField;
        
        private string DescriptionField;
        
        private string CommentField;
        
        private bool SummaryScanIndicatorField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ScanType
        {
            get
            {
                return this.ScanTypeField;
            }
            set
            {
                this.ScanTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public purolator.com.pws.datatypes.v1.PIN PIN
        {
            get
            {
                return this.PINField;
            }
            set
            {
                this.PINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public purolator.com.pws.datatypes.v1.Depot Depot
        {
            get
            {
                return this.DepotField;
            }
            set
            {
                this.DepotField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string ScanDate
        {
            get
            {
                return this.ScanDateField;
            }
            set
            {
                this.ScanDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string ScanTime
        {
            get
            {
                return this.ScanTimeField;
            }
            set
            {
                this.ScanTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string Comment
        {
            get
            {
                return this.CommentField;
            }
            set
            {
                this.CommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool SummaryScanIndicator
        {
            get
            {
                return this.SummaryScanIndicatorField;
            }
            set
            {
                this.SummaryScanIndicatorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Depot", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class Depot : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InternationalOutboundScan", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class InternationalOutboundScan : purolator.com.pws.datatypes.v1.Scan
    {
        
        private purolator.com.pws.datatypes.v1.InternationalOutboundScanDetails ScanDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public purolator.com.pws.datatypes.v1.InternationalOutboundScanDetails ScanDetails
        {
            get
            {
                return this.ScanDetailsField;
            }
            set
            {
                this.ScanDetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UndeliverableScan", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class UndeliverableScan : purolator.com.pws.datatypes.v1.Scan
    {
        
        private purolator.com.pws.datatypes.v1.UndeliverableScanDetails ScanDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public purolator.com.pws.datatypes.v1.UndeliverableScanDetails ScanDetails
        {
            get
            {
                return this.ScanDetailsField;
            }
            set
            {
                this.ScanDetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OnDeliveryScan", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class OnDeliveryScan : purolator.com.pws.datatypes.v1.Scan
    {
        
        private purolator.com.pws.datatypes.v1.OnDeliveryScanDetails ScanDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public purolator.com.pws.datatypes.v1.OnDeliveryScanDetails ScanDetails
        {
            get
            {
                return this.ScanDetailsField;
            }
            set
            {
                this.ScanDetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProofOfPickUpScan", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class ProofOfPickUpScan : purolator.com.pws.datatypes.v1.Scan
    {
        
        private purolator.com.pws.datatypes.v1.ProofOfPickUpScanDetails ScanDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public purolator.com.pws.datatypes.v1.ProofOfPickUpScanDetails ScanDetails
        {
            get
            {
                return this.ScanDetailsField;
            }
            set
            {
                this.ScanDetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveryScan", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class DeliveryScan : purolator.com.pws.datatypes.v1.Scan
    {
        
        private purolator.com.pws.datatypes.v1.DeliveryScanDetails ScanDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public purolator.com.pws.datatypes.v1.DeliveryScanDetails ScanDetails
        {
            get
            {
                return this.ScanDetailsField;
            }
            set
            {
                this.ScanDetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InternationalOutboundScanDetails", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class InternationalOutboundScanDetails : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DestinationPostalCodeField;
        
        private string AirportCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DestinationPostalCode
        {
            get
            {
                return this.DestinationPostalCodeField;
            }
            set
            {
                this.DestinationPostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string AirportCode
        {
            get
            {
                return this.AirportCodeField;
            }
            set
            {
                this.AirportCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UndeliverableScanDetails", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class UndeliverableScanDetails : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AttemptedDeliveryAddressField;
        
        private string DeliveryCompanyNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AttemptedDeliveryAddress
        {
            get
            {
                return this.AttemptedDeliveryAddressField;
            }
            set
            {
                this.AttemptedDeliveryAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DeliveryCompanyName
        {
            get
            {
                return this.DeliveryCompanyNameField;
            }
            set
            {
                this.DeliveryCompanyNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OnDeliveryScanDetails", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class OnDeliveryScanDetails : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DeliveryAddressField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DeliveryAddress
        {
            get
            {
                return this.DeliveryAddressField;
            }
            set
            {
                this.DeliveryAddressField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProofOfPickUpScanDetails", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class ProofOfPickUpScanDetails : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string PickUpConfirmationNumberField;
        
        private purolator.com.pws.datatypes.v1.Address PickUpAddressField;
        
        private string PickUpContactNameField;
        
        private string PickUpCompanyNameField;
        
        private string PickUpLocationField;
        
        private string CommitedDeliveryDateField;
        
        private string PremiumServiceTextField;
        
        private string ProductTypeTextField;
        
        private string SpecialHandlingTextField;
        
        private string PaymentTypeTextField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PickUpConfirmationNumber
        {
            get
            {
                return this.PickUpConfirmationNumberField;
            }
            set
            {
                this.PickUpConfirmationNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public purolator.com.pws.datatypes.v1.Address PickUpAddress
        {
            get
            {
                return this.PickUpAddressField;
            }
            set
            {
                this.PickUpAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string PickUpContactName
        {
            get
            {
                return this.PickUpContactNameField;
            }
            set
            {
                this.PickUpContactNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string PickUpCompanyName
        {
            get
            {
                return this.PickUpCompanyNameField;
            }
            set
            {
                this.PickUpCompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string PickUpLocation
        {
            get
            {
                return this.PickUpLocationField;
            }
            set
            {
                this.PickUpLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string CommitedDeliveryDate
        {
            get
            {
                return this.CommitedDeliveryDateField;
            }
            set
            {
                this.CommitedDeliveryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string PremiumServiceText
        {
            get
            {
                return this.PremiumServiceTextField;
            }
            set
            {
                this.PremiumServiceTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public string ProductTypeText
        {
            get
            {
                return this.ProductTypeTextField;
            }
            set
            {
                this.ProductTypeTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public string SpecialHandlingText
        {
            get
            {
                return this.SpecialHandlingTextField;
            }
            set
            {
                this.SpecialHandlingTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public string PaymentTypeText
        {
            get
            {
                return this.PaymentTypeTextField;
            }
            set
            {
                this.PaymentTypeTextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NameField;
        
        private string CompanyField;
        
        private string DepartmentField;
        
        private string StreetNumberField;
        
        private string StreetSuffixField;
        
        private string StreetNameField;
        
        private string StreetTypeField;
        
        private string StreetDirectionField;
        
        private string SuiteField;
        
        private string FloorField;
        
        private string StreetAddress2Field;
        
        private string StreetAddress3Field;
        
        private string CityField;
        
        private string ProvinceField;
        
        private string CountryField;
        
        private string PostalCodeField;
        
        private purolator.com.pws.datatypes.v1.PhoneNumber PhoneNumberField;
        
        private purolator.com.pws.datatypes.v1.PhoneNumber FaxNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Company
        {
            get
            {
                return this.CompanyField;
            }
            set
            {
                this.CompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Department
        {
            get
            {
                return this.DepartmentField;
            }
            set
            {
                this.DepartmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string StreetNumber
        {
            get
            {
                return this.StreetNumberField;
            }
            set
            {
                this.StreetNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string StreetSuffix
        {
            get
            {
                return this.StreetSuffixField;
            }
            set
            {
                this.StreetSuffixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string StreetName
        {
            get
            {
                return this.StreetNameField;
            }
            set
            {
                this.StreetNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string StreetType
        {
            get
            {
                return this.StreetTypeField;
            }
            set
            {
                this.StreetTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string StreetDirection
        {
            get
            {
                return this.StreetDirectionField;
            }
            set
            {
                this.StreetDirectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string Suite
        {
            get
            {
                return this.SuiteField;
            }
            set
            {
                this.SuiteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string Floor
        {
            get
            {
                return this.FloorField;
            }
            set
            {
                this.FloorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string StreetAddress2
        {
            get
            {
                return this.StreetAddress2Field;
            }
            set
            {
                this.StreetAddress2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string StreetAddress3
        {
            get
            {
                return this.StreetAddress3Field;
            }
            set
            {
                this.StreetAddress3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public string Province
        {
            get
            {
                return this.ProvinceField;
            }
            set
            {
                this.ProvinceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public purolator.com.pws.datatypes.v1.PhoneNumber PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public purolator.com.pws.datatypes.v1.PhoneNumber FaxNumber
        {
            get
            {
                return this.FaxNumberField;
            }
            set
            {
                this.FaxNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneNumber", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class PhoneNumber : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CountryCodeField;
        
        private string AreaCodeField;
        
        private string PhoneField;
        
        private string ExtensionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CountryCode
        {
            get
            {
                return this.CountryCodeField;
            }
            set
            {
                this.CountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string AreaCode
        {
            get
            {
                return this.AreaCodeField;
            }
            set
            {
                this.AreaCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Extension
        {
            get
            {
                return this.ExtensionField;
            }
            set
            {
                this.ExtensionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveryScanDetails", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class DeliveryScanDetails : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DeliverySignatureField;
        
        private string SignatureImageField;
        
        private int SignatureImageSizeField;
        
        private purolator.com.pws.datatypes.v1.SignatureImageFormat SignatureImageFormatField;
        
        private string DeliveryAddressField;
        
        private string DeliveryCompanyNameField;
        
        private string PremiumServiceTextField;
        
        private string ProductTypeTextField;
        
        private string SpecialHandlingTextField;
        
        private string PaymentTypeTextField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DeliverySignature
        {
            get
            {
                return this.DeliverySignatureField;
            }
            set
            {
                this.DeliverySignatureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SignatureImage
        {
            get
            {
                return this.SignatureImageField;
            }
            set
            {
                this.SignatureImageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SignatureImageSize
        {
            get
            {
                return this.SignatureImageSizeField;
            }
            set
            {
                this.SignatureImageSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public purolator.com.pws.datatypes.v1.SignatureImageFormat SignatureImageFormat
        {
            get
            {
                return this.SignatureImageFormatField;
            }
            set
            {
                this.SignatureImageFormatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string DeliveryAddress
        {
            get
            {
                return this.DeliveryAddressField;
            }
            set
            {
                this.DeliveryAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string DeliveryCompanyName
        {
            get
            {
                return this.DeliveryCompanyNameField;
            }
            set
            {
                this.DeliveryCompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string PremiumServiceText
        {
            get
            {
                return this.PremiumServiceTextField;
            }
            set
            {
                this.PremiumServiceTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public string ProductTypeText
        {
            get
            {
                return this.ProductTypeTextField;
            }
            set
            {
                this.ProductTypeTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public string SpecialHandlingText
        {
            get
            {
                return this.SpecialHandlingTextField;
            }
            set
            {
                this.SpecialHandlingTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public string PaymentTypeText
        {
            get
            {
                return this.PaymentTypeTextField;
            }
            set
            {
                this.PaymentTypeTextField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignatureImageFormat", Namespace="http://purolator.com/pws/datatypes/v1")]
    public enum SignatureImageFormat : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GIF = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bitmap = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OriginalUncompressed = 2,
    }
}
namespace www.microsoft.com.practices.EnterpriseLibrary._2007._01.wcf.validation
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationFault", Namespace="http://www.microsoft.com/practices/EnterpriseLibrary/2007/01/wcf/validation")]
    public partial class ValidationFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Microsoft.Practices.EnterpriseLibrary.Validation.Integration.WCF.ValidationDetail[] DetailsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Practices.EnterpriseLibrary.Validation.Integration.WCF.ValidationDetail[] Details
        {
            get
            {
                return this.DetailsField;
            }
            set
            {
                this.DetailsField = value;
            }
        }
    }
}
namespace Microsoft.Practices.EnterpriseLibrary.Validation.Integration.WCF
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationDetail", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Practices.EnterpriseLibrary.Val" +
        "idation.Integration.WCF")]
    public partial class ValidationDetail : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string KeyField;
        
        private string MessageField;
        
        private string TagField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tag
        {
            get
            {
                return this.TagField;
            }
            set
            {
                this.TagField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://purolator.com/pws/service/v1", ConfigurationName="TrackingServiceContract")]
public interface TrackingServiceContract
{
    
    // CODEGEN: Generating message contract since the operation TrackPackagesByPin is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="http://purolator.com/pws/service/v1/TrackPackagesByPin", ReplyAction="http://purolator.com/pws/service/v1/TrackingServiceContract/TrackPackagesByPinRes" +
        "ponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.microsoft.com.practices.EnterpriseLibrary._2007._01.wcf.validation.ValidationFault), Action="http://purolator.com/pws/service/v1/TrackingServiceContract/TrackPackagesByPinVal" +
        "idationFaultFault", Name="ValidationFault", Namespace="http://www.microsoft.com/practices/EnterpriseLibrary/2007/01/wcf/validation")]
    TrackPackagesByPinResponse TrackPackagesByPin(TrackPackagesByPinRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://purolator.com/pws/service/v1/TrackPackagesByPin", ReplyAction="http://purolator.com/pws/service/v1/TrackingServiceContract/TrackPackagesByPinRes" +
        "ponse")]
    System.Threading.Tasks.Task<TrackPackagesByPinResponse> TrackPackagesByPinAsync(TrackPackagesByPinRequest request);
    
    // CODEGEN: Generating message contract since the operation TrackPackagesByReference is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="http://purolator.com/pws/service/v1/TrackPackagesByReference", ReplyAction="http://purolator.com/pws/service/v1/TrackingServiceContract/TrackPackagesByRefere" +
        "nceResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.microsoft.com.practices.EnterpriseLibrary._2007._01.wcf.validation.ValidationFault), Action="http://purolator.com/pws/service/v1/TrackingServiceContract/TrackPackagesByRefere" +
        "nceValidationFaultFault", Name="ValidationFault", Namespace="http://www.microsoft.com/practices/EnterpriseLibrary/2007/01/wcf/validation")]
    TrackPackagesByReferenceResponse TrackPackagesByReference(TrackPackagesByReferenceRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://purolator.com/pws/service/v1/TrackPackagesByReference", ReplyAction="http://purolator.com/pws/service/v1/TrackingServiceContract/TrackPackagesByRefere" +
        "nceResponse")]
    System.Threading.Tasks.Task<TrackPackagesByReferenceResponse> TrackPackagesByReferenceAsync(TrackPackagesByReferenceRequest request);
    
    // CODEGEN: Generating message contract since the operation GetDeliveryDetails is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="http://purolator.com/pws/service/v1/GetDeliveryDetails", ReplyAction="http://purolator.com/pws/service/v1/TrackingServiceContract/GetDeliveryDetailsRes" +
        "ponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.microsoft.com.practices.EnterpriseLibrary._2007._01.wcf.validation.ValidationFault), Action="http://purolator.com/pws/service/v1/TrackingServiceContract/GetDeliveryDetailsVal" +
        "idationFaultFault", Name="ValidationFault", Namespace="http://www.microsoft.com/practices/EnterpriseLibrary/2007/01/wcf/validation")]
    GetDeliveryDetailsResponse GetDeliveryDetails(GetDeliveryDetailsRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://purolator.com/pws/service/v1/GetDeliveryDetails", ReplyAction="http://purolator.com/pws/service/v1/TrackingServiceContract/GetDeliveryDetailsRes" +
        "ponse")]
    System.Threading.Tasks.Task<GetDeliveryDetailsResponse> GetDeliveryDetailsAsync(GetDeliveryDetailsRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class TrackPackagesByPinRequest
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public purolator.com.pws.datatypes.v1.RequestContext RequestContext;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="TrackPackagesByPinRequest", Namespace="http://purolator.com/pws/datatypes/v1", Order=0)]
    public purolator.com.pws.datatypes.v1.TrackPackagesByPinRequestContainer TrackPackagesByPinRequest1;
    
    public TrackPackagesByPinRequest()
    {
    }
    
    public TrackPackagesByPinRequest(purolator.com.pws.datatypes.v1.RequestContext RequestContext, purolator.com.pws.datatypes.v1.TrackPackagesByPinRequestContainer TrackPackagesByPinRequest1)
    {
        this.RequestContext = RequestContext;
        this.TrackPackagesByPinRequest1 = TrackPackagesByPinRequest1;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class TrackPackagesByPinResponse
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public purolator.com.pws.datatypes.v1.ResponseContext ResponseContext;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="TrackPackagesByPinResponse", Namespace="http://purolator.com/pws/datatypes/v1", Order=0)]
    public purolator.com.pws.datatypes.v1.TrackPackagesByPinResponseContainer TrackPackagesByPinResponse1;
    
    public TrackPackagesByPinResponse()
    {
    }
    
    public TrackPackagesByPinResponse(purolator.com.pws.datatypes.v1.ResponseContext ResponseContext, purolator.com.pws.datatypes.v1.TrackPackagesByPinResponseContainer TrackPackagesByPinResponse1)
    {
        this.ResponseContext = ResponseContext;
        this.TrackPackagesByPinResponse1 = TrackPackagesByPinResponse1;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class TrackPackagesByReferenceRequest
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public purolator.com.pws.datatypes.v1.RequestContext RequestContext;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="TrackPackagesByReferenceRequest", Namespace="http://purolator.com/pws/datatypes/v1", Order=0)]
    public purolator.com.pws.datatypes.v1.TrackPackagesByReferenceRequestContainer TrackPackagesByReferenceRequest1;
    
    public TrackPackagesByReferenceRequest()
    {
    }
    
    public TrackPackagesByReferenceRequest(purolator.com.pws.datatypes.v1.RequestContext RequestContext, purolator.com.pws.datatypes.v1.TrackPackagesByReferenceRequestContainer TrackPackagesByReferenceRequest1)
    {
        this.RequestContext = RequestContext;
        this.TrackPackagesByReferenceRequest1 = TrackPackagesByReferenceRequest1;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class TrackPackagesByReferenceResponse
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public purolator.com.pws.datatypes.v1.ResponseContext ResponseContext;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="TrackPackagesByReferenceResponse", Namespace="http://purolator.com/pws/datatypes/v1", Order=0)]
    public purolator.com.pws.datatypes.v1.TrackPackagesByReferenceResponseContainer TrackPackagesByReferenceResponse1;
    
    public TrackPackagesByReferenceResponse()
    {
    }
    
    public TrackPackagesByReferenceResponse(purolator.com.pws.datatypes.v1.ResponseContext ResponseContext, purolator.com.pws.datatypes.v1.TrackPackagesByReferenceResponseContainer TrackPackagesByReferenceResponse1)
    {
        this.ResponseContext = ResponseContext;
        this.TrackPackagesByReferenceResponse1 = TrackPackagesByReferenceResponse1;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetDeliveryDetailsRequest
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public purolator.com.pws.datatypes.v1.RequestContext RequestContext;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeliveryDetailsRequest", Namespace="http://purolator.com/pws/datatypes/v1", Order=0)]
    public purolator.com.pws.datatypes.v1.GetDeliveryDetailsRequestContainer GetDeliveryDetailsRequest1;
    
    public GetDeliveryDetailsRequest()
    {
    }
    
    public GetDeliveryDetailsRequest(purolator.com.pws.datatypes.v1.RequestContext RequestContext, purolator.com.pws.datatypes.v1.GetDeliveryDetailsRequestContainer GetDeliveryDetailsRequest1)
    {
        this.RequestContext = RequestContext;
        this.GetDeliveryDetailsRequest1 = GetDeliveryDetailsRequest1;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetDeliveryDetailsResponse
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public purolator.com.pws.datatypes.v1.ResponseContext ResponseContext;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeliveryDetailsResponse", Namespace="http://purolator.com/pws/datatypes/v1", Order=0)]
    public purolator.com.pws.datatypes.v1.GetDeliveryDetailsResponseContainer GetDeliveryDetailsResponse1;
    
    public GetDeliveryDetailsResponse()
    {
    }
    
    public GetDeliveryDetailsResponse(purolator.com.pws.datatypes.v1.ResponseContext ResponseContext, purolator.com.pws.datatypes.v1.GetDeliveryDetailsResponseContainer GetDeliveryDetailsResponse1)
    {
        this.ResponseContext = ResponseContext;
        this.GetDeliveryDetailsResponse1 = GetDeliveryDetailsResponse1;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface TrackingServiceContractChannel : TrackingServiceContract, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class TrackingServiceContractClient : System.ServiceModel.ClientBase<TrackingServiceContract>, TrackingServiceContract
{
    
    public TrackingServiceContractClient()
    {
    }
    
    public TrackingServiceContractClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public TrackingServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TrackingServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TrackingServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    TrackPackagesByPinResponse TrackingServiceContract.TrackPackagesByPin(TrackPackagesByPinRequest request)
    {
        return base.Channel.TrackPackagesByPin(request);
    }
    
    public purolator.com.pws.datatypes.v1.ResponseContext TrackPackagesByPin(purolator.com.pws.datatypes.v1.RequestContext RequestContext, purolator.com.pws.datatypes.v1.TrackPackagesByPinRequestContainer TrackPackagesByPinRequest1, out purolator.com.pws.datatypes.v1.TrackPackagesByPinResponseContainer TrackPackagesByPinResponse1)
    {
        TrackPackagesByPinRequest inValue = new TrackPackagesByPinRequest();
        inValue.RequestContext = RequestContext;
        inValue.TrackPackagesByPinRequest1 = TrackPackagesByPinRequest1;
        TrackPackagesByPinResponse retVal = ((TrackingServiceContract)(this)).TrackPackagesByPin(inValue);
        TrackPackagesByPinResponse1 = retVal.TrackPackagesByPinResponse1;
        return retVal.ResponseContext;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<TrackPackagesByPinResponse> TrackingServiceContract.TrackPackagesByPinAsync(TrackPackagesByPinRequest request)
    {
        return base.Channel.TrackPackagesByPinAsync(request);
    }
    
    public System.Threading.Tasks.Task<TrackPackagesByPinResponse> TrackPackagesByPinAsync(purolator.com.pws.datatypes.v1.RequestContext RequestContext, purolator.com.pws.datatypes.v1.TrackPackagesByPinRequestContainer TrackPackagesByPinRequest1)
    {
        TrackPackagesByPinRequest inValue = new TrackPackagesByPinRequest();
        inValue.RequestContext = RequestContext;
        inValue.TrackPackagesByPinRequest1 = TrackPackagesByPinRequest1;
        return ((TrackingServiceContract)(this)).TrackPackagesByPinAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    TrackPackagesByReferenceResponse TrackingServiceContract.TrackPackagesByReference(TrackPackagesByReferenceRequest request)
    {
        return base.Channel.TrackPackagesByReference(request);
    }
    
    public purolator.com.pws.datatypes.v1.ResponseContext TrackPackagesByReference(purolator.com.pws.datatypes.v1.RequestContext RequestContext, purolator.com.pws.datatypes.v1.TrackPackagesByReferenceRequestContainer TrackPackagesByReferenceRequest1, out purolator.com.pws.datatypes.v1.TrackPackagesByReferenceResponseContainer TrackPackagesByReferenceResponse1)
    {
        TrackPackagesByReferenceRequest inValue = new TrackPackagesByReferenceRequest();
        inValue.RequestContext = RequestContext;
        inValue.TrackPackagesByReferenceRequest1 = TrackPackagesByReferenceRequest1;
        TrackPackagesByReferenceResponse retVal = ((TrackingServiceContract)(this)).TrackPackagesByReference(inValue);
        TrackPackagesByReferenceResponse1 = retVal.TrackPackagesByReferenceResponse1;
        return retVal.ResponseContext;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<TrackPackagesByReferenceResponse> TrackingServiceContract.TrackPackagesByReferenceAsync(TrackPackagesByReferenceRequest request)
    {
        return base.Channel.TrackPackagesByReferenceAsync(request);
    }
    
    public System.Threading.Tasks.Task<TrackPackagesByReferenceResponse> TrackPackagesByReferenceAsync(purolator.com.pws.datatypes.v1.RequestContext RequestContext, purolator.com.pws.datatypes.v1.TrackPackagesByReferenceRequestContainer TrackPackagesByReferenceRequest1)
    {
        TrackPackagesByReferenceRequest inValue = new TrackPackagesByReferenceRequest();
        inValue.RequestContext = RequestContext;
        inValue.TrackPackagesByReferenceRequest1 = TrackPackagesByReferenceRequest1;
        return ((TrackingServiceContract)(this)).TrackPackagesByReferenceAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetDeliveryDetailsResponse TrackingServiceContract.GetDeliveryDetails(GetDeliveryDetailsRequest request)
    {
        return base.Channel.GetDeliveryDetails(request);
    }
    
    public purolator.com.pws.datatypes.v1.ResponseContext GetDeliveryDetails(purolator.com.pws.datatypes.v1.RequestContext RequestContext, purolator.com.pws.datatypes.v1.GetDeliveryDetailsRequestContainer GetDeliveryDetailsRequest1, out purolator.com.pws.datatypes.v1.GetDeliveryDetailsResponseContainer GetDeliveryDetailsResponse1)
    {
        GetDeliveryDetailsRequest inValue = new GetDeliveryDetailsRequest();
        inValue.RequestContext = RequestContext;
        inValue.GetDeliveryDetailsRequest1 = GetDeliveryDetailsRequest1;
        GetDeliveryDetailsResponse retVal = ((TrackingServiceContract)(this)).GetDeliveryDetails(inValue);
        GetDeliveryDetailsResponse1 = retVal.GetDeliveryDetailsResponse1;
        return retVal.ResponseContext;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetDeliveryDetailsResponse> TrackingServiceContract.GetDeliveryDetailsAsync(GetDeliveryDetailsRequest request)
    {
        return base.Channel.GetDeliveryDetailsAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetDeliveryDetailsResponse> GetDeliveryDetailsAsync(purolator.com.pws.datatypes.v1.RequestContext RequestContext, purolator.com.pws.datatypes.v1.GetDeliveryDetailsRequestContainer GetDeliveryDetailsRequest1)
    {
        GetDeliveryDetailsRequest inValue = new GetDeliveryDetailsRequest();
        inValue.RequestContext = RequestContext;
        inValue.GetDeliveryDetailsRequest1 = GetDeliveryDetailsRequest1;
        return ((TrackingServiceContract)(this)).GetDeliveryDetailsAsync(inValue);
    }
}
