//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestContext", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class RequestContext : object
    {
        
        private string VersionField;
        
        private TrackingService.Language LanguageField;
        
        private string GroupIDField;
        
        private string RequestReferenceField;
        
        private string UserTokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public TrackingService.Language Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string GroupID
        {
            get
            {
                return this.GroupIDField;
            }
            set
            {
                this.GroupIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string RequestReference
        {
            get
            {
                return this.RequestReferenceField;
            }
            set
            {
                this.RequestReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string UserToken
        {
            get
            {
                return this.UserTokenField;
            }
            set
            {
                this.UserTokenField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Language", Namespace="http://purolator.com/pws/datatypes/v1")]
    public enum Language : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        en = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fr = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseContext", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class ResponseContext : object
    {
        
        private string ResponseReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ResponseReference
        {
            get
            {
                return this.ResponseReferenceField;
            }
            set
            {
                this.ResponseReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestContainer", Namespace="http://purolator.com/pws/datatypes/v1")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TrackingService.TrackPackagesByReferenceRequestContainer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TrackingService.GetDeliveryDetailsRequestContainer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TrackingService.TrackPackagesByPinRequestContainer))]
    public partial class RequestContainer : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrackPackagesByReferenceRequestContainer", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class TrackPackagesByReferenceRequestContainer : TrackingService.RequestContainer
    {
        
        private TrackingService.TrackPackageByReferenceSearchCriteria TrackPackageByReferenceSearchCriteriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TrackingService.TrackPackageByReferenceSearchCriteria TrackPackageByReferenceSearchCriteria
        {
            get
            {
                return this.TrackPackageByReferenceSearchCriteriaField;
            }
            set
            {
                this.TrackPackageByReferenceSearchCriteriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDeliveryDetailsRequestContainer", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class GetDeliveryDetailsRequestContainer : TrackingService.RequestContainer
    {
        
        private TrackingService.PIN PINField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TrackingService.PIN PIN
        {
            get
            {
                return this.PINField;
            }
            set
            {
                this.PINField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrackPackagesByPinRequestContainer", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class TrackPackagesByPinRequestContainer : TrackingService.RequestContainer
    {
        
        private TrackingService.PIN[] PINsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TrackingService.PIN[] PINs
        {
            get
            {
                return this.PINsField;
            }
            set
            {
                this.PINsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PIN", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class PIN : object
    {
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrackPackageByReferenceSearchCriteria", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class TrackPackageByReferenceSearchCriteria : object
    {
        
        private string ReferenceField;
        
        private string DestinationPostalCodeField;
        
        private string DestinationCountryCodeField;
        
        private string BillingAccountNumberField;
        
        private string ShipmentFromDateField;
        
        private string ShipmentToDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Reference
        {
            get
            {
                return this.ReferenceField;
            }
            set
            {
                this.ReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string DestinationPostalCode
        {
            get
            {
                return this.DestinationPostalCodeField;
            }
            set
            {
                this.DestinationPostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string DestinationCountryCode
        {
            get
            {
                return this.DestinationCountryCodeField;
            }
            set
            {
                this.DestinationCountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string BillingAccountNumber
        {
            get
            {
                return this.BillingAccountNumberField;
            }
            set
            {
                this.BillingAccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string ShipmentFromDate
        {
            get
            {
                return this.ShipmentFromDateField;
            }
            set
            {
                this.ShipmentFromDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string ShipmentToDate
        {
            get
            {
                return this.ShipmentToDateField;
            }
            set
            {
                this.ShipmentToDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseContainer", Namespace="http://purolator.com/pws/datatypes/v1")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TrackingService.TrackPackagesByReferenceResponseContainer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TrackingService.GetDeliveryDetailsResponseContainer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TrackingService.TrackPackagesByPinResponseContainer))]
    public partial class ResponseContainer : object
    {
        
        private TrackingService.ResponseInformation ResponseInformationField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TrackingService.ResponseInformation ResponseInformation
        {
            get
            {
                return this.ResponseInformationField;
            }
            set
            {
                this.ResponseInformationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseInformation", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class ResponseInformation : object
    {
        
        private TrackingService.Error[] ErrorsField;
        
        private TrackingService.InformationalMessage[] InformationalMessagesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TrackingService.Error[] Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TrackingService.InformationalMessage[] InformationalMessages
        {
            get
            {
                return this.InformationalMessagesField;
            }
            set
            {
                this.InformationalMessagesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrackPackagesByReferenceResponseContainer", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class TrackPackagesByReferenceResponseContainer : TrackingService.ResponseContainer
    {
        
        private TrackingService.TrackingInformation[] TrackingInformationListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackingService.TrackingInformation[] TrackingInformationList
        {
            get
            {
                return this.TrackingInformationListField;
            }
            set
            {
                this.TrackingInformationListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDeliveryDetailsResponseContainer", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class GetDeliveryDetailsResponseContainer : TrackingService.ResponseContainer
    {
        
        private TrackingService.DeliveryScan DeliveryDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackingService.DeliveryScan DeliveryDetails
        {
            get
            {
                return this.DeliveryDetailsField;
            }
            set
            {
                this.DeliveryDetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrackPackagesByPinResponseContainer", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class TrackPackagesByPinResponseContainer : TrackingService.ResponseContainer
    {
        
        private TrackingService.TrackingInformation[] TrackingInformationListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackingService.TrackingInformation[] TrackingInformationList
        {
            get
            {
                return this.TrackingInformationListField;
            }
            set
            {
                this.TrackingInformationListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrackingInformation", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class TrackingInformation : object
    {
        
        private TrackingService.PIN PINField;
        
        private TrackingService.Scan[] ScansField;
        
        private TrackingService.ResponseInformation ResponseInformationField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TrackingService.PIN PIN
        {
            get
            {
                return this.PINField;
            }
            set
            {
                this.PINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackingService.Scan[] Scans
        {
            get
            {
                return this.ScansField;
            }
            set
            {
                this.ScansField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public TrackingService.ResponseInformation ResponseInformation
        {
            get
            {
                return this.ResponseInformationField;
            }
            set
            {
                this.ResponseInformationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class Error : object
    {
        
        private string CodeField;
        
        private string DescriptionField;
        
        private string AdditionalInformationField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string AdditionalInformation
        {
            get
            {
                return this.AdditionalInformationField;
            }
            set
            {
                this.AdditionalInformationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InformationalMessage", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class InformationalMessage : object
    {
        
        private string CodeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Scan", Namespace="http://purolator.com/pws/datatypes/v1")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TrackingService.InternationalOutboundScan))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TrackingService.UndeliverableScan))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TrackingService.OnDeliveryScan))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TrackingService.ProofOfPickUpScan))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TrackingService.DeliveryScan))]
    public partial class Scan : object
    {
        
        private string ScanTypeField;
        
        private TrackingService.PIN PINField;
        
        private TrackingService.Depot DepotField;
        
        private string ScanDateField;
        
        private string ScanTimeField;
        
        private string DescriptionField;
        
        private string CommentField;
        
        private bool SummaryScanIndicatorField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ScanType
        {
            get
            {
                return this.ScanTypeField;
            }
            set
            {
                this.ScanTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public TrackingService.PIN PIN
        {
            get
            {
                return this.PINField;
            }
            set
            {
                this.PINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public TrackingService.Depot Depot
        {
            get
            {
                return this.DepotField;
            }
            set
            {
                this.DepotField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string ScanDate
        {
            get
            {
                return this.ScanDateField;
            }
            set
            {
                this.ScanDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string ScanTime
        {
            get
            {
                return this.ScanTimeField;
            }
            set
            {
                this.ScanTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string Comment
        {
            get
            {
                return this.CommentField;
            }
            set
            {
                this.CommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool SummaryScanIndicator
        {
            get
            {
                return this.SummaryScanIndicatorField;
            }
            set
            {
                this.SummaryScanIndicatorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Depot", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class Depot : object
    {
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InternationalOutboundScan", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class InternationalOutboundScan : TrackingService.Scan
    {
        
        private TrackingService.InternationalOutboundScanDetails ScanDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TrackingService.InternationalOutboundScanDetails ScanDetails
        {
            get
            {
                return this.ScanDetailsField;
            }
            set
            {
                this.ScanDetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UndeliverableScan", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class UndeliverableScan : TrackingService.Scan
    {
        
        private TrackingService.UndeliverableScanDetails ScanDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TrackingService.UndeliverableScanDetails ScanDetails
        {
            get
            {
                return this.ScanDetailsField;
            }
            set
            {
                this.ScanDetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OnDeliveryScan", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class OnDeliveryScan : TrackingService.Scan
    {
        
        private TrackingService.OnDeliveryScanDetails ScanDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TrackingService.OnDeliveryScanDetails ScanDetails
        {
            get
            {
                return this.ScanDetailsField;
            }
            set
            {
                this.ScanDetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProofOfPickUpScan", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class ProofOfPickUpScan : TrackingService.Scan
    {
        
        private TrackingService.ProofOfPickUpScanDetails ScanDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TrackingService.ProofOfPickUpScanDetails ScanDetails
        {
            get
            {
                return this.ScanDetailsField;
            }
            set
            {
                this.ScanDetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveryScan", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class DeliveryScan : TrackingService.Scan
    {
        
        private TrackingService.DeliveryScanDetails ScanDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TrackingService.DeliveryScanDetails ScanDetails
        {
            get
            {
                return this.ScanDetailsField;
            }
            set
            {
                this.ScanDetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InternationalOutboundScanDetails", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class InternationalOutboundScanDetails : object
    {
        
        private string DestinationPostalCodeField;
        
        private string AirportCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DestinationPostalCode
        {
            get
            {
                return this.DestinationPostalCodeField;
            }
            set
            {
                this.DestinationPostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string AirportCode
        {
            get
            {
                return this.AirportCodeField;
            }
            set
            {
                this.AirportCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UndeliverableScanDetails", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class UndeliverableScanDetails : object
    {
        
        private string AttemptedDeliveryAddressField;
        
        private string DeliveryCompanyNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AttemptedDeliveryAddress
        {
            get
            {
                return this.AttemptedDeliveryAddressField;
            }
            set
            {
                this.AttemptedDeliveryAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DeliveryCompanyName
        {
            get
            {
                return this.DeliveryCompanyNameField;
            }
            set
            {
                this.DeliveryCompanyNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OnDeliveryScanDetails", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class OnDeliveryScanDetails : object
    {
        
        private string DeliveryAddressField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DeliveryAddress
        {
            get
            {
                return this.DeliveryAddressField;
            }
            set
            {
                this.DeliveryAddressField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProofOfPickUpScanDetails", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class ProofOfPickUpScanDetails : object
    {
        
        private string PickUpConfirmationNumberField;
        
        private TrackingService.Address PickUpAddressField;
        
        private string PickUpContactNameField;
        
        private string PickUpCompanyNameField;
        
        private string PickUpLocationField;
        
        private string CommitedDeliveryDateField;
        
        private string PremiumServiceTextField;
        
        private string ProductTypeTextField;
        
        private string SpecialHandlingTextField;
        
        private string PaymentTypeTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PickUpConfirmationNumber
        {
            get
            {
                return this.PickUpConfirmationNumberField;
            }
            set
            {
                this.PickUpConfirmationNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public TrackingService.Address PickUpAddress
        {
            get
            {
                return this.PickUpAddressField;
            }
            set
            {
                this.PickUpAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string PickUpContactName
        {
            get
            {
                return this.PickUpContactNameField;
            }
            set
            {
                this.PickUpContactNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string PickUpCompanyName
        {
            get
            {
                return this.PickUpCompanyNameField;
            }
            set
            {
                this.PickUpCompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string PickUpLocation
        {
            get
            {
                return this.PickUpLocationField;
            }
            set
            {
                this.PickUpLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string CommitedDeliveryDate
        {
            get
            {
                return this.CommitedDeliveryDateField;
            }
            set
            {
                this.CommitedDeliveryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string PremiumServiceText
        {
            get
            {
                return this.PremiumServiceTextField;
            }
            set
            {
                this.PremiumServiceTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public string ProductTypeText
        {
            get
            {
                return this.ProductTypeTextField;
            }
            set
            {
                this.ProductTypeTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public string SpecialHandlingText
        {
            get
            {
                return this.SpecialHandlingTextField;
            }
            set
            {
                this.SpecialHandlingTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public string PaymentTypeText
        {
            get
            {
                return this.PaymentTypeTextField;
            }
            set
            {
                this.PaymentTypeTextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class Address : object
    {
        
        private string NameField;
        
        private string CompanyField;
        
        private string DepartmentField;
        
        private string StreetNumberField;
        
        private string StreetSuffixField;
        
        private string StreetNameField;
        
        private string StreetTypeField;
        
        private string StreetDirectionField;
        
        private string SuiteField;
        
        private string FloorField;
        
        private string StreetAddress2Field;
        
        private string StreetAddress3Field;
        
        private string CityField;
        
        private string ProvinceField;
        
        private string CountryField;
        
        private string PostalCodeField;
        
        private TrackingService.PhoneNumber PhoneNumberField;
        
        private TrackingService.PhoneNumber FaxNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Company
        {
            get
            {
                return this.CompanyField;
            }
            set
            {
                this.CompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Department
        {
            get
            {
                return this.DepartmentField;
            }
            set
            {
                this.DepartmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string StreetNumber
        {
            get
            {
                return this.StreetNumberField;
            }
            set
            {
                this.StreetNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string StreetSuffix
        {
            get
            {
                return this.StreetSuffixField;
            }
            set
            {
                this.StreetSuffixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string StreetName
        {
            get
            {
                return this.StreetNameField;
            }
            set
            {
                this.StreetNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string StreetType
        {
            get
            {
                return this.StreetTypeField;
            }
            set
            {
                this.StreetTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string StreetDirection
        {
            get
            {
                return this.StreetDirectionField;
            }
            set
            {
                this.StreetDirectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string Suite
        {
            get
            {
                return this.SuiteField;
            }
            set
            {
                this.SuiteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string Floor
        {
            get
            {
                return this.FloorField;
            }
            set
            {
                this.FloorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string StreetAddress2
        {
            get
            {
                return this.StreetAddress2Field;
            }
            set
            {
                this.StreetAddress2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string StreetAddress3
        {
            get
            {
                return this.StreetAddress3Field;
            }
            set
            {
                this.StreetAddress3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public string Province
        {
            get
            {
                return this.ProvinceField;
            }
            set
            {
                this.ProvinceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public TrackingService.PhoneNumber PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public TrackingService.PhoneNumber FaxNumber
        {
            get
            {
                return this.FaxNumberField;
            }
            set
            {
                this.FaxNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneNumber", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class PhoneNumber : object
    {
        
        private string CountryCodeField;
        
        private string AreaCodeField;
        
        private string PhoneField;
        
        private string ExtensionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CountryCode
        {
            get
            {
                return this.CountryCodeField;
            }
            set
            {
                this.CountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string AreaCode
        {
            get
            {
                return this.AreaCodeField;
            }
            set
            {
                this.AreaCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Extension
        {
            get
            {
                return this.ExtensionField;
            }
            set
            {
                this.ExtensionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveryScanDetails", Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class DeliveryScanDetails : object
    {
        
        private string DeliverySignatureField;
        
        private string SignatureImageField;
        
        private int SignatureImageSizeField;
        
        private TrackingService.SignatureImageFormat SignatureImageFormatField;
        
        private string DeliveryAddressField;
        
        private string DeliveryCompanyNameField;
        
        private string PremiumServiceTextField;
        
        private string ProductTypeTextField;
        
        private string SpecialHandlingTextField;
        
        private string PaymentTypeTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DeliverySignature
        {
            get
            {
                return this.DeliverySignatureField;
            }
            set
            {
                this.DeliverySignatureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SignatureImage
        {
            get
            {
                return this.SignatureImageField;
            }
            set
            {
                this.SignatureImageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SignatureImageSize
        {
            get
            {
                return this.SignatureImageSizeField;
            }
            set
            {
                this.SignatureImageSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public TrackingService.SignatureImageFormat SignatureImageFormat
        {
            get
            {
                return this.SignatureImageFormatField;
            }
            set
            {
                this.SignatureImageFormatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string DeliveryAddress
        {
            get
            {
                return this.DeliveryAddressField;
            }
            set
            {
                this.DeliveryAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string DeliveryCompanyName
        {
            get
            {
                return this.DeliveryCompanyNameField;
            }
            set
            {
                this.DeliveryCompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string PremiumServiceText
        {
            get
            {
                return this.PremiumServiceTextField;
            }
            set
            {
                this.PremiumServiceTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public string ProductTypeText
        {
            get
            {
                return this.ProductTypeTextField;
            }
            set
            {
                this.ProductTypeTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public string SpecialHandlingText
        {
            get
            {
                return this.SpecialHandlingTextField;
            }
            set
            {
                this.SpecialHandlingTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public string PaymentTypeText
        {
            get
            {
                return this.PaymentTypeTextField;
            }
            set
            {
                this.PaymentTypeTextField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignatureImageFormat", Namespace="http://purolator.com/pws/datatypes/v1")]
    public enum SignatureImageFormat : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GIF = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bitmap = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OriginalUncompressed = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationFault", Namespace="http://www.microsoft.com/practices/EnterpriseLibrary/2007/01/wcf/validation")]
    public partial class ValidationFault : object
    {
        
        private TrackingService.ValidationDetail[] DetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackingService.ValidationDetail[] Details
        {
            get
            {
                return this.DetailsField;
            }
            set
            {
                this.DetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationDetail", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Practices.EnterpriseLibrary.Val" +
        "idation.Integration.WCF")]
    public partial class ValidationDetail : object
    {
        
        private string KeyField;
        
        private string MessageField;
        
        private string TagField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tag
        {
            get
            {
                return this.TagField;
            }
            set
            {
                this.TagField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://purolator.com/pws/service/v1", ConfigurationName="TrackingService.TrackingServiceContract")]
    public interface TrackingServiceContract
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://purolator.com/pws/service/v1/TrackPackagesByPin", ReplyAction="http://purolator.com/pws/service/v1/TrackingServiceContract/TrackPackagesByPinRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TrackingService.ValidationFault), Action="http://purolator.com/pws/service/v1/TrackingServiceContract/TrackPackagesByPinVal" +
            "idationFaultFault", Name="ValidationFault", Namespace="http://www.microsoft.com/practices/EnterpriseLibrary/2007/01/wcf/validation")]
        TrackingService.TrackPackagesByPinResponse TrackPackagesByPin(TrackingService.TrackPackagesByPinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://purolator.com/pws/service/v1/TrackPackagesByPin", ReplyAction="http://purolator.com/pws/service/v1/TrackingServiceContract/TrackPackagesByPinRes" +
            "ponse")]
        System.Threading.Tasks.Task<TrackingService.TrackPackagesByPinResponse> TrackPackagesByPinAsync(TrackingService.TrackPackagesByPinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://purolator.com/pws/service/v1/TrackPackagesByReference", ReplyAction="http://purolator.com/pws/service/v1/TrackingServiceContract/TrackPackagesByRefere" +
            "nceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TrackingService.ValidationFault), Action="http://purolator.com/pws/service/v1/TrackingServiceContract/TrackPackagesByRefere" +
            "nceValidationFaultFault", Name="ValidationFault", Namespace="http://www.microsoft.com/practices/EnterpriseLibrary/2007/01/wcf/validation")]
        TrackingService.TrackPackagesByReferenceResponse TrackPackagesByReference(TrackingService.TrackPackagesByReferenceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://purolator.com/pws/service/v1/TrackPackagesByReference", ReplyAction="http://purolator.com/pws/service/v1/TrackingServiceContract/TrackPackagesByRefere" +
            "nceResponse")]
        System.Threading.Tasks.Task<TrackingService.TrackPackagesByReferenceResponse> TrackPackagesByReferenceAsync(TrackingService.TrackPackagesByReferenceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://purolator.com/pws/service/v1/GetDeliveryDetails", ReplyAction="http://purolator.com/pws/service/v1/TrackingServiceContract/GetDeliveryDetailsRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TrackingService.ValidationFault), Action="http://purolator.com/pws/service/v1/TrackingServiceContract/GetDeliveryDetailsVal" +
            "idationFaultFault", Name="ValidationFault", Namespace="http://www.microsoft.com/practices/EnterpriseLibrary/2007/01/wcf/validation")]
        TrackingService.GetDeliveryDetailsResponse GetDeliveryDetails(TrackingService.GetDeliveryDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://purolator.com/pws/service/v1/GetDeliveryDetails", ReplyAction="http://purolator.com/pws/service/v1/TrackingServiceContract/GetDeliveryDetailsRes" +
            "ponse")]
        System.Threading.Tasks.Task<TrackingService.GetDeliveryDetailsResponse> GetDeliveryDetailsAsync(TrackingService.GetDeliveryDetailsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TrackPackagesByPinRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
        public TrackingService.RequestContext RequestContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TrackPackagesByPinRequest", Namespace="http://purolator.com/pws/datatypes/v1", Order=0)]
        public TrackingService.TrackPackagesByPinRequestContainer TrackPackagesByPinRequest1;
        
        public TrackPackagesByPinRequest()
        {
        }
        
        public TrackPackagesByPinRequest(TrackingService.RequestContext RequestContext, TrackingService.TrackPackagesByPinRequestContainer TrackPackagesByPinRequest1)
        {
            this.RequestContext = RequestContext;
            this.TrackPackagesByPinRequest1 = TrackPackagesByPinRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TrackPackagesByPinResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
        public TrackingService.ResponseContext ResponseContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TrackPackagesByPinResponse", Namespace="http://purolator.com/pws/datatypes/v1", Order=0)]
        public TrackingService.TrackPackagesByPinResponseContainer TrackPackagesByPinResponse1;
        
        public TrackPackagesByPinResponse()
        {
        }
        
        public TrackPackagesByPinResponse(TrackingService.ResponseContext ResponseContext, TrackingService.TrackPackagesByPinResponseContainer TrackPackagesByPinResponse1)
        {
            this.ResponseContext = ResponseContext;
            this.TrackPackagesByPinResponse1 = TrackPackagesByPinResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TrackPackagesByReferenceRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
        public TrackingService.RequestContext RequestContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TrackPackagesByReferenceRequest", Namespace="http://purolator.com/pws/datatypes/v1", Order=0)]
        public TrackingService.TrackPackagesByReferenceRequestContainer TrackPackagesByReferenceRequest1;
        
        public TrackPackagesByReferenceRequest()
        {
        }
        
        public TrackPackagesByReferenceRequest(TrackingService.RequestContext RequestContext, TrackingService.TrackPackagesByReferenceRequestContainer TrackPackagesByReferenceRequest1)
        {
            this.RequestContext = RequestContext;
            this.TrackPackagesByReferenceRequest1 = TrackPackagesByReferenceRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TrackPackagesByReferenceResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
        public TrackingService.ResponseContext ResponseContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TrackPackagesByReferenceResponse", Namespace="http://purolator.com/pws/datatypes/v1", Order=0)]
        public TrackingService.TrackPackagesByReferenceResponseContainer TrackPackagesByReferenceResponse1;
        
        public TrackPackagesByReferenceResponse()
        {
        }
        
        public TrackPackagesByReferenceResponse(TrackingService.ResponseContext ResponseContext, TrackingService.TrackPackagesByReferenceResponseContainer TrackPackagesByReferenceResponse1)
        {
            this.ResponseContext = ResponseContext;
            this.TrackPackagesByReferenceResponse1 = TrackPackagesByReferenceResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeliveryDetailsRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
        public TrackingService.RequestContext RequestContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeliveryDetailsRequest", Namespace="http://purolator.com/pws/datatypes/v1", Order=0)]
        public TrackingService.GetDeliveryDetailsRequestContainer GetDeliveryDetailsRequest1;
        
        public GetDeliveryDetailsRequest()
        {
        }
        
        public GetDeliveryDetailsRequest(TrackingService.RequestContext RequestContext, TrackingService.GetDeliveryDetailsRequestContainer GetDeliveryDetailsRequest1)
        {
            this.RequestContext = RequestContext;
            this.GetDeliveryDetailsRequest1 = GetDeliveryDetailsRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeliveryDetailsResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
        public TrackingService.ResponseContext ResponseContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeliveryDetailsResponse", Namespace="http://purolator.com/pws/datatypes/v1", Order=0)]
        public TrackingService.GetDeliveryDetailsResponseContainer GetDeliveryDetailsResponse1;
        
        public GetDeliveryDetailsResponse()
        {
        }
        
        public GetDeliveryDetailsResponse(TrackingService.ResponseContext ResponseContext, TrackingService.GetDeliveryDetailsResponseContainer GetDeliveryDetailsResponse1)
        {
            this.ResponseContext = ResponseContext;
            this.GetDeliveryDetailsResponse1 = GetDeliveryDetailsResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface TrackingServiceContractChannel : TrackingService.TrackingServiceContract, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class TrackingServiceContractClient : System.ServiceModel.ClientBase<TrackingService.TrackingServiceContract>, TrackingService.TrackingServiceContract
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TrackingServiceContractClient() : 
                base(TrackingServiceContractClient.GetDefaultBinding(), TrackingServiceContractClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.TrackingServiceEndpoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TrackingServiceContractClient(EndpointConfiguration endpointConfiguration) : 
                base(TrackingServiceContractClient.GetBindingForEndpoint(endpointConfiguration), TrackingServiceContractClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TrackingServiceContractClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TrackingServiceContractClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TrackingServiceContractClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TrackingServiceContractClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TrackingServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public TrackingService.TrackPackagesByPinResponse TrackPackagesByPin(TrackingService.TrackPackagesByPinRequest request)
        {
            return base.Channel.TrackPackagesByPin(request);
        }
        
        public System.Threading.Tasks.Task<TrackingService.TrackPackagesByPinResponse> TrackPackagesByPinAsync(TrackingService.TrackPackagesByPinRequest request)
        {
            return base.Channel.TrackPackagesByPinAsync(request);
        }
        
        public TrackingService.TrackPackagesByReferenceResponse TrackPackagesByReference(TrackingService.TrackPackagesByReferenceRequest request)
        {
            return base.Channel.TrackPackagesByReference(request);
        }
        
        public System.Threading.Tasks.Task<TrackingService.TrackPackagesByReferenceResponse> TrackPackagesByReferenceAsync(TrackingService.TrackPackagesByReferenceRequest request)
        {
            return base.Channel.TrackPackagesByReferenceAsync(request);
        }
        
        public TrackingService.GetDeliveryDetailsResponse GetDeliveryDetails(TrackingService.GetDeliveryDetailsRequest request)
        {
            return base.Channel.GetDeliveryDetails(request);
        }
        
        public System.Threading.Tasks.Task<TrackingService.GetDeliveryDetailsResponse> GetDeliveryDetailsAsync(TrackingService.GetDeliveryDetailsRequest request)
        {
            return base.Channel.GetDeliveryDetailsAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TrackingServiceEndpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TrackingServiceEndpoint))
            {
                return new System.ServiceModel.EndpointAddress("https://devwebservices.purolator.com/EWS/V1/Tracking/TrackingService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TrackingServiceContractClient.GetBindingForEndpoint(EndpointConfiguration.TrackingServiceEndpoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TrackingServiceContractClient.GetEndpointAddress(EndpointConfiguration.TrackingServiceEndpoint);
        }
        
        public enum EndpointConfiguration
        {
            
            TrackingServiceEndpoint,
        }
    }
}
